CREATE TABLE IF NOT EXISTS WEATHER  (
    CITY VARCHAR(50),
    TIME_STAMP LONG,
    FEELS_LIKE DOUBLE,
    HUMIDITY DOUBLE,
    PRESSURE DOUBLE,
    TEMP DOUBLE,
    TEMP_MIN DOUBLE,
    TEMP_MAX DOUBLE,
    DESCRIPTION VARCHAR(50),
    ICON VARCHAR(50),
    CASHED_TIME TIMESTAMP
    );


